services:
    eco.admin.activity:
        class: App\Admin\ActivityAdmin
        arguments: [~, App\Entity\Activity, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: menu.activity }
        calls:
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
            - [ addChild, ['@eco.admin.participation', 'activity']]
    eco.admin.degree:
        class: App\Admin\DegreeAdmin
        arguments: [~, App\Entity\Degree, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: menu.degree }
        calls:
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
    eco.admin.idea:
        class: App\Admin\IdeaAdmin
        arguments: [~, 'App\Entity\Idea', 'App\Controller\Sonata\IdeaCRUDController']
        tags:
            - { name: sonata.admin, manager_type: orm, label: menu.idea }
        calls:
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
    eco.admin.participation:
        class: App\Admin\ParticipationAdmin
        arguments: [~, App\Entity\Participation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: menu.participation }
        calls:
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
    eco.admin.telegram_chat_private:
        class: App\Admin\TelegramChatPrivateAdmin
        arguments: [ ~, App\Entity\TelegramChatPrivate, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: menu.telegram_chat_private }
    eco.admin.telegram_chat_super_group:
        class: App\Admin\TelegramChatSuperGroupAdmin
        arguments: [ ~, App\Entity\TelegramChatSuperGroup, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: menu.telegram_chat_super_group }
    eco.admin.telegram_chat_group:
        class: App\Admin\TelegramChatGroupAdmin
        arguments: [ ~, App\Entity\TelegramChatGroup, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: menu.telegram_chat_group }
    eco.admin.telegram_chat_channel:
        class: App\Admin\TelegramChatChannelAdmin
        arguments: [ ~, App\Entity\TelegramChatChannel, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: menu.telegram_chat_channel }
        calls:
            - [ setBotman, ['@botman']]

twig:
    form_themes:
        - 'SonataCoreBundle:Form:datepicker.html.twig'
