#!/usr/bin/env bash

echo "CEO pre commit hook start"

PHP_CS_FIXER="vendor/bin/php-cs-fixer"
HAS_PHP_CS_FIXER=false
HAS_JSHINT=false

if [ -x vendor/bin/php-cs-fixer ]; then
    HAS_PHP_CS_FIXER=true
fi

if [ -x node_modules/gulp-jshint ]; then
    HAS_JSHINT=true
fi

if $HAS_PHP_CS_FIXER; then
    git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
        $PHP_CS_FIXER fix --verbose "$line";
        git add "$line";
    done
else
    echo ""
    echo "Please install php-cs-fixer, e.g.:"
    echo ""
    echo "  composer require --dev fabpot/php-cs-fixer:dev-master"
    echo ""
fi

if $HAS_JSHINT; then
    git status --porcelain | grep -e '^\s*[AM]\(.*\).js$' | cut -c 3- | while read line; do gulp jshint --filter=${line}; done;
fi

echo "CEO pre commit hook finish"
