# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    base_path: "build/ckeditor4"
    js_path:   "build/ckeditor4/ckeditor.js"
    default_config: simple_toolbar
    configs:
        simple_toolbar:
            basicEntities: false
            entities_greek: false
            entities_latin: false
            entities_additional: ''
            fillEmptyBlocks: false
            tabSpaces: 0
            toolbar:
                - ['Bold', 'Italic', 'Strike', 'Link']
                - ['BulletedList', 'NumberedList', '-', 'Outdent', 'Indent']
                - ['Copy', 'Paste', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['Source']
