leogout_seo:
    # By default, the SEO generators services are not loaded if you don't configure them. The following default configuration
    # loads the services but they won't render anything.
    # See https://github.com/leogout/SeoBundle#configuration-reference to configure them.
    # See https://github.com/leogout/SeoBundle#setting-values-dynamically to use them directly in your controller.
    general:
        title: 'Ideas | Aula de Software Libre'
        description: |
            Portal de propuesta de ideas y actividades del Aula de Software
            Libre de la Universidad de Córdoba
    basic: ~
    og:
        type: 'website'
        url: 'https://ideas.aulasoftwarelibre.uco.es/'
        image: 'https://ideas.aulasoftwarelibre.uco.es/assets/images/seo.png'
    twitter:
        card: 'summary_large_image'
        site: '@aulasl'
        image: 'https://ideas.aulasoftwarelibre.uco.es/assets/images/seo.png'
