version: "3.4"

services:
    php:
        build:
            context: .
            target: idea_php
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s
        env_file:
            -   ./.env.prod.local

    httpd:
        build:
            context: .
            target: idea_httpd
        depends_on:
            - php
        ports:
            - "8081:80"

    db:
        image: mariadb:10.3
        env_file:
            -   ./.env.prod.local
