# config/services_dev.yaml
services:
    mailer.dev.set_recipients:
        class: Symfony\Component\Mailer\EventListener\EnvelopeListener
        tags: ['kernel.event_subscriber']
        arguments:
            $sender: '%env(MAIL_FROM)%'
            $recipients: ['%env(MAIL_TO)%']
