<?php

/*
 * This file is part of the ceo project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use Sonata\FormatterBundle\Form\Type\SimpleFormatterType;

class IdeaAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $form)
    {
        $form
            ->add('title', null, [
            ])
            ->add('description', SimpleFormatterType::class, [
                'format' => 'richhtml',
                'attr' => ['rows' => 20],
            ])
            ->add('closed', null, [
            ])
            ->add('owner', null, [
                'placeholder' => 'Seleccione un usuario',
            ])
            ->add('group', null, [
                'placeholder' => 'Seleccione un grupo',
            ])
        ;
    }

    protected function configureListFields(ListMapper $list)
    {
        $list
            ->addIdentifier('title', null, [
                'route' => ['name' => 'show'],
            ])
            ->add('closed', null, [
                'editable' => true,
            ])
            ->add('createdAt', null, [
            ])
            ->add('_action', 'actions', [
                'actions' => [
                    'show' => [],
                    'edit' => [],
                ],
            ])
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
    }

    protected function configureShowFields(ShowMapper $show)
    {
        $show
            ->add('title', null, [
            ])
            ->add('description', null, [
                'safe' => true,
            ])
            ->add('closed', null, [
            ])
            ->add('createdAt', null, [
            ])
        ;
    }
}
