<?php

return array (
  'APP_SECRET' => NULL,
  'CLIENT_GITHUB_ID' => NULL,
  'CLIENT_GITHUB_SECRET' => NULL,
  'CLIENT_GOOGLE_ID' => NULL,
  'CLIENT_GOOGLE_SECRET' => NULL,
  'CLIENT_UCO_ID' => NULL,
  'CLIENT_UCO_SECRET' => NULL,
  'DATABASE_URL' => NULL,
  'MAILER_DSN' => NULL,
);
